# -*- coding: utf-8 -*-
"""dai_assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JLGd5umNq8_OvIr9PIyM07fyPxcnvV_x
"""

!pip install openai
!pip install gradio
!pip install chromadb

import os
os.environ['API_GATEWAY_KEY'] = "Pa1a8NxLVl5rG2DgbtDj"

import os
from openai import OpenAI

OPENAI_API_KEY = os.environ["API_GATEWAY_KEY"]

client = OpenAI(
    base_url="https://k7uffyg03f.execute-api.us-east-1.amazonaws.com/prod/openai/v1",
    api_key="any value",
    default_headers={"x-api-key": OPENAI_API_KEY},
)

import os
os.makedirs("chroma_db", exist_ok=True)

RESTRICTED_TOPICS = [
    "cat", "dog",
    "horoscope", "zodiac",
    "taylor swift"
]

def guardrails(user_message):
    lower = user_message.lower()

    # Topic restriction
    for topic in RESTRICTED_TOPICS:
        if topic in lower:
            return "I'm not allowed to discuss that topic."

    # System prompt protection
    if "system prompt" in lower or "ignore previous instructions" in lower:
        return "I cannot reveal or modify my internal instructions."

    return None

import requests

def weather_service():
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": 43.7,
        "longitude": -79.4,
        "current_weather": True
    }

    r = requests.get(url, params=params)
    data = r.json()

    temp = data["current_weather"]["temperature"]
    wind = data["current_weather"]["windspeed"]

    # Transform output (NOT verbatim)
    return f"In Toronto right now, it's about {temp}°C with winds moving at {wind} km/h."

import chromadb
from chromadb.utils import embedding_functions
import os

chroma_client = chromadb.PersistentClient(path="./chroma_db")

BASE_URL = "https://k7uffyg03f.execute-api.us-east-1.amazonaws.com/prod/openai/v1" # Define BASE_URL here

embedding_function = embedding_functions.OpenAIEmbeddingFunction(
    api_key=os.environ["API_GATEWAY_KEY"],
    model_name="text-embedding-3-small",
    api_base=BASE_URL  # ☀ Important for gateway
)

collection = chroma_client.get_or_create_collection(
    name="knowledge_base",
    embedding_function=embedding_function
)

# Add small dataset (run once)
collection.add(
    documents=[
        "Artificial Intelligence is the simulation of human intelligence.",
        "Machine learning is a subset of AI.",
        "Neural networks are inspired by biological neurons.",
        "Deep learning uses multi-layer neural networks."
    ],
    ids=["1","2","3","4"]
)

def semantic_search(query):
    results = collection.query(
        query_texts=[query],
        n_results=2
    )

    context = "\n".join(results["documents"][0])

    prompt = f"""
    Use this context to answer the question:

    {context}

    Question: {query}
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

def calculate(expression):
    try:
        return str(eval(expression))
    except:
        return "Invalid expression."

import gradio as gr

SYSTEM_PROMPT = """
You are Nova, a witty but professional AI assistant.
You are concise, friendly, and insightful.
"""

conversation_history = []

def main_router(user_input):

    # 1️⃣ Guardrails first
    blocked = guardrails(user_input)
    if blocked:
        return blocked

    lower = user_input.lower()

    # 2️⃣ Service 1
    if "weather" in lower:
        return weather_service()

    # 3️⃣ Service 3
    elif user_input.startswith("calculate"):
        expr = user_input.replace("calculate", "").strip()
        return calculate(expr)

    # 4️⃣ Service 2
    elif "ai" in lower or "machine learning" in lower:
        return semantic_search(user_input)

    # 5️⃣ Default LLM with memory
    else:
        conversation_history.append({"role": "user", "content": user_input})

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "system", "content": SYSTEM_PROMPT}] + conversation_history
        )

        reply = response.choices[0].message.content

        conversation_history.append({"role": "assistant", "content": reply})

        # Optional memory limit
        if len(conversation_history) > 10:
            conversation_history.pop(0)

        return reply

def respond(message, chat_history):
    reply = main_router(message)
    chat_history.append((message, reply))
    return "", chat_history

with gr.Blocks() as demo:
    gr.Markdown("# 🤖 Nova AI Assistant")
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    clear.click(lambda: None, None, chatbot)

demo.launch()