# -*- coding: utf-8 -*-
"""dai_assignment_1.7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3L41nUV3BuBlO1tKf0l-whcGpFCsgjK
"""

!pip install openai langchain langchain-community pydantic deepeval pymupdf tiktoken

import os
os.environ['API_GATEWAY_KEY'] = "Pa1a8NxLVl5rG2DgbtDj"

import os
from openai import OpenAI
from getpass import getpass

# Ask for your API Gateway key (secure)
os.environ["API_GATEWAY_KEY"] = getpass("Enter your API Gateway Key: ")

client = OpenAI(
    base_url="https://k7uffyg03f.execute-api.us-east-1.amazonaws.com/prod/openai/v1",
    api_key="dummy-value",  # ignored
    default_headers={"x-api-key": os.environ["API_GATEWAY_KEY"]},
)

from langchain_community.document_loaders import PyMuPDFLoader
from IPython.display import FileLink

# Upload the PDF to Colab first (or use files.upload) if you haven't already.
# Example: from google.colab import files; files.upload()
# You can also verify the file exists using FileLink
FileLink('Managing Oneself_Drucker_HBR.pdf')

# Uncomment the following lines after you have uploaded the PDF file.
loader = PyMuPDFLoader("Managing Oneself_Drucker_HBR.pdf")  # make sure PDF is in Colab workspace
docs = loader.load()

# # Combine all pages into one string
document_text = "\n".join([page.page_content for page in docs])

print(document_text[:1000])  # preview first 1000 chars

from pydantic import BaseModel

class ArticleSummary(BaseModel):
    Author: str
    Title: str
    Relevance: str
    Summary: str
    Tone: str
    InputTokens: int
    OutputTokens: int

# Developer instructions (fixed)
developer_prompt = """
You are an expert summarizer.
- Extract Author and Title.
- Write a concise summary under 1000 tokens.
- Use Victorian English tone.
- Explain relevance for AI professionals.
- Ensure clarity, coherence, and structure.
- Do not fabricate content.
"""

# User prompt — dynamically inject document content
user_prompt_template = """
Here is the article content:

{context}

Please generate the structured output according to the Pydantic model.
"""

# Inject document (truncate for token safety if needed)
user_prompt = user_prompt_template.format(context=document_text[:15000])

import json

response = client.chat.completions.create(
    model="gpt-4o-mini",  # NOT GPT-5
    messages=[
        {"role": "developer", "content": developer_prompt},
        {"role": "user", "content": user_prompt}
    ],
    response_format={
        "type": "json_schema",
        "json_schema": {
            "name": "ArticleSummary",
            "schema": ArticleSummary.model_json_schema()
        }
    }
)

structured_output = json.loads(response.choices[0].message.content)

summary_object = ArticleSummary(
    Author=structured_output["Author"],
    Title=structured_output["Title"],
    Relevance=structured_output["Relevance"],
    Summary=structured_output["Summary"],
    Tone=structured_output["Tone"],
    InputTokens=response.usage.prompt_tokens,
    OutputTokens=response.usage.completion_tokens
)

summary_object

from deepeval.metrics import SummarizationMetric, GEval
from deepeval.test_case import LLMTestCase

test_case = LLMTestCase(
    input=document_text[:10000],
    actual_output=summary_object.Summary
)

import os
import deepeval
from openai import OpenAI
from deepeval.models import GPTModel

# Unset OPENAI_API_KEY to prevent it from being picked up automatically by DeepEval's OpenAI client
if 'OPENAI_API_KEY' in os.environ:
    del os.environ['OPENAI_API_KEY']

# Instantiate GPTModel with the necessary parameters for the API Gateway
deepeval_llm = GPTModel(
    model="gpt-4o-mini",
    api_key="dummy-value", # This is the dummy key for the API Gateway setup
    base_url="https://k7uffyg03f.execute-api.us-east-1.amazonaws.com/prod/openai/v1",
    # Pass default_headers directly to GPTModel, which should forward it to the OpenAI client
    default_headers={"x-api-key": os.environ["API_GATEWAY_KEY"]}
)

# The set_llm was causing an AttributeError, and passing llm=deepeval_llm was causing a TypeError.
# The SummarizationMetric's constructor expects the custom LLM via the 'model' argument.
summarization_metric = SummarizationMetric(
    model=deepeval_llm, # Pass the custom LLM directly using the 'model' argument
    assessment_questions=[
        "Does the summary capture the core thesis of the article?",
        "Are the main arguments accurately represented?",
        "Is important information omitted?",
        "Is the summary factually consistent with the source?",
        "Is the summary concise without redundancy?"
    ]
)

# Run evaluation
summarization_metric.measure(test_case)

print("Summarization Score:", summarization_metric.score)
print("Summarization Reason:", summarization_metric.reason)

from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCaseParams

coherence_metric = GEval(
    name="Coherence",
    criteria="Evaluate clarity, logical flow, and structure.",
    model=deepeval_llm, # Pass the custom LLM here
    evaluation_params={LLMTestCaseParams.ACTUAL_OUTPUT: "Summary"} # Correctly specify which part of the test case to evaluate
)

coherence_metric.measure(test_case)

print("Coherence Score:", coherence_metric.score)
print("Coherence Reason:", coherence_metric.reason)

from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCaseParams

tonality_metric = GEval(
    name="Tonality",
    criteria="Evaluate whether the Victorian English tone is consistently applied.",
    model=deepeval_llm, # Pass the custom LLM here
    evaluation_params={LLMTestCaseParams.ACTUAL_OUTPUT: "Summary"} # Specify which part of the test case to evaluate
)

tonality_metric.measure(test_case)

print("Tonality Score:", tonality_metric.score)
print("Tonality Reason:", tonality_metric.reason)

from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCaseParams

safety_metric = GEval(
    name="Safety",
    criteria="Evaluate if the content is safe and non-harmful.",
    model=deepeval_llm, # Pass the custom LLM here
    evaluation_params={LLMTestCaseParams.ACTUAL_OUTPUT: "Summary"} # Specify which part of the test case to evaluate
)

safety_metric.measure(test_case)

print("Safety Score:", safety_metric.score)
print("Safety Reason:", safety_metric.reason)

evaluation_results = {
    "SummarizationScore": summarization_metric.score,
    "SummarizationReason": summarization_metric.reason,
    "CoherenceScore": coherence_metric.score,
    "CoherenceReason": coherence_metric.reason,
    "TonalityScore": tonality_metric.score,
    "TonalityReason": tonality_metric.reason,
    "SafetyScore": safety_metric.score,
    "SafetyReason": safety_metric.reason
}

evaluation_results

enhancement_prompt = f"""
Original Summary:
{summary_object.Summary}

Evaluation Feedback:
{evaluation_results}

Please improve the summary while:
- Preserving factual accuracy
- Improving weak scoring areas
- Maintaining Victorian English tone
- Keeping under 1000 tokens
"""

improved_response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "developer", "content": developer_prompt},
        {"role": "user", "content": enhancement_prompt}
    ]
)

improved_summary = improved_response.choices[0].message.content

improved_test_case = LLMTestCase(
    input=document_text[:10000],
    actual_output=improved_summary
)

summarization_metric.measure(improved_test_case)
coherence_metric.measure(improved_test_case)
tonality_metric.measure(improved_test_case)
safety_metric.measure(improved_test_case)

comparison = {
    "Original Summarization": evaluation_results["SummarizationScore"],
    "Improved Summarization": summarization_metric.score,
    "Original Coherence": evaluation_results["CoherenceScore"],
    "Improved Coherence": coherence_metric.score,
    "Original Tonality": evaluation_results["TonalityScore"],
    "Improved Tonality": tonality_metric.score
}

comparison